### ISSUE TITLE
MUC support

### ISSUE THREAD

**Issue by COM8** [UWPX/UWPX-Client#10]
Add support for MUC chats.

### ToDo:
- [X] MUC browser
- [X] Join MUCs
- [X] Create MUCs
- [X] Send MUC messages
- [X] Join bookmarked MUCs
- [X] Bookmark MUCs
- [X] Manage MUC configuration
- [x] Accept / send MUC invitations
- [x] Manage MUC occupants
