### ISSUE TITLE
UI Overhaul

### ISSUE THREAD

**Issue by COM8** [UWPX/UWPX-Client#50]
A complete UI overhaule is needed to improve the UI responsiveness and fix related issues.

### Related issues:
- [x] #5
- [x] #28
- [x] #38
- [x] #39 
- [x] #40 
- [x] #45 
- [x] #69

### ToDo (updated 28.03.2020):
- [x] Move to a MVVM desing
    - [x] Chat page
        - [x] Design
        - [x] UI
        - [x] Logic
        - [x] Low performance device optimizations (phones)
    - [x] Settings overview page
        - [x] Design
        - [x] UI
        - [x] Logic
        - [x] Low performance device optimizations (phones)
    - [x] Other settings pages
        - [x] Account settings page 
            - [x] Design
            - [x] UI
            - [x] Logic
            - [x] Low performance device optimizations (phones)
        - [x] Personalize settings page 
            - [x] Design
            - [x] UI
            - [x] Logic
            - [x] Low performance device optimizations (phones)
        - [x] Chat settings page
            - [x] Design
            - [x] UI
            - [x] Logic
            - [x] Low performance device optimizations (phones)
        - [x] Data settings page
            - [x] Design
            - [x] UI
            - [x] Logic
            - [x] Low performance device optimizations (phones)
        - [x] Background Tasks settings page 
            - [x] Design
            - [x] UI
            - [x] Logic
            - [x] Low performance device optimizations (phones)
        - [x] ~Security settings page~
            - [x] ~Design~
            - [x] ~UI~
            - [x] ~Logic~
            - [x] ~Low performance device optimizations (phones)~
        - [x] Donate page 
            - [x] Design
            - [x] UI
            - [x] Logic
            - [x] Low performance device optimizations (phones)
        - [x] Misc settings page
            - [x] Design
            - [x] UI
            - [x] Logic
            - [x] Low performance device optimizations (phones)
    - [x] ~Manage bookmarks page~
        - [x] ~Design~
        - [x] ~UI~
        - [x] ~Logic~
        - [x] ~Low performance device optimizations (phones)~
    - [x] ~Browse MUCs page~
        - [x] ~Design~
        - [x] ~UI~
        - [x] ~Logic~
        - [x] ~Low performance device optimizations (phones)~
    - [x] Add account page
        - [x] Design
        - [x] UI
        - [x] Logic
        - [x] Low performance device optimizations (phones)
    - [x] Contact info page
        - [x] Design
        - [x] UI
        - [x] Logic
        - [x] Low performance device optimizations (phones)
    - [x] MUC info page
        - [x] Design
        - [x] UI
        - [x] Logic
        - [x] Low performance device optimizations (phones)
    - [x] Add chat dialog
        - [x] Design
        - [x] UI
        - [x] Logic
        - [x] Low performance device optimizations (phones)
    - [x] Add MUC dialog
        - [x] Design
        - [x] UI
        - [x] Logic
        - [x] Low performance device optimizations (phones)
    - [x] Change presence dialog
        - [x] Design
        - [x] UI
        - [x] Logic
        - [x] Low performance device optimizations (phones)
- [x] Add [Fluent Design](https://www.microsoft.com/design/fluent/) support
- [x] ~~Add localisation support~~
- [x] Improve general UI performance
- [x] Improve UI usability
- [x] Proper light and dark theme support
- [x] New app logo
- [x] Update logo to the new XMPP logo ([uwpx.github.io#1](https://github.com/UWPX/uwpx.github.io/issues/1))

### Want more up to date news?
Follow [@UWPX_APP](https://twitter.com/UWPX_APP) on ![Twitter](http://i.imgur.com/wWzX9uB.png).

**Comment by Echolon** [comment]
Thank you very much for your efforts! Looking forward!

Have a happy new XMPP year 2019! Guten Rutsch!

My +1 for the new UI as well as the background!

**Comment by COM8** [comment]
Here some new preview images of the **WIP** UI overhaul.
The white theme still has some contrast problems, but it's getting there.
Let me know if you have any suggestions!

![dark_overview](https://user-images.githubusercontent.com/11741404/51429848-80a89900-1c13-11e9-8b46-ceb1abc6467f.png)
![dark_settings](https://user-images.githubusercontent.com/11741404/51429849-80a89900-1c13-11e9-831a-e462bed68afc.png)
![dark_accounts](https://user-images.githubusercontent.com/11741404/51429850-80a89900-1c13-11e9-8267-2b76cd165b5d.png)
![dark_misc](https://user-images.githubusercontent.com/11741404/51429851-80a89900-1c13-11e9-87d3-bdc6b923b4c4.png)
![light_misc](https://user-images.githubusercontent.com/11741404/51429852-81412f80-1c13-11e9-930a-e906c667c9a0.png)
![light_accounts](https://user-images.githubusercontent.com/11741404/51429853-81412f80-1c13-11e9-863b-3fbd0db223c0.png)
![light_overview](https://user-images.githubusercontent.com/11741404/51429854-81412f80-1c13-11e9-8c56-3ddbebd87da2.png)

**Comment by Echolon** [comment]
Looks AWESOME!

You probably saw it yourself, but the text 'Select a chat to view' in the bright mode cannot be read nicely.

Cheers

**Comment by COM8** [comment]
Yeah :D

**Comment by COM8** [comment]
Since there won't be a new release this month (mainly because I have to prepare for a lot of exams right now) I decided to write a small status update about what I've done since the last pictures ~14 days ago:

* I've updated the initial comment to show, more accurate, the progress of the UI overhaule
* I've been working on a "new" UWPX logo
* The accounts page now actually has logic behind it
* I've started adding more logic for the chats page (add/remove bookmark, add remove from roster, ...)

### The plan for March:
With the March release  (v.0.14.0.0) I want the new UI to be at a point where it's more or less usable.
You will be able to select the new or old UI on the initial app start (don't worry you can still switch between them via the settings 😉).
Since I'm writing exams until the 1st of March, plan with an update around the 10th of March.

### Here is the new UWPX logo:
![310](https://user-images.githubusercontent.com/11741404/52161770-b432fb00-26ca-11e9-9880-cf9b917600a5.png)

### And for comparison the old one:
![310](https://user-images.githubusercontent.com/11741404/52161773-b85f1880-26ca-11e9-8ea0-b6413f37be2f.png)

Let me know if you have any suggestions how I can make the new logo even better looking (since I'm only a programmer 😉 not an artist)!

**Comment by Echolon** [comment]
Awsaum! ;)

All the best for your exams, I like the new logo!

**Comment by COM8** [comment]
Since I was not really happy with the way the "new" UWPX logo was scaling I decided to work on a new logo again...

Here it is:

![uwpx_logo_v3](https://user-images.githubusercontent.com/11741404/56378817-72681a00-620e-11e9-8b73-9431f529d516.png)

The new logo solves these issues and also matches the new simple Windows 10 logo style.

![icons_windows](https://user-images.githubusercontent.com/11741404/56378745-39c84080-620e-11e9-8ef9-7be6bbb18d05.png)
(Source: [Meet the new icons for Office 365](https://www.youtube.com/watch?v=YplAU5myNP4))

## Examples:
Here are a few more example of the new logo on action:

### Splash screen PC:
![splash](https://user-images.githubusercontent.com/11741404/56379390-f1118700-620f-11e9-8cef-eda38bf1171e.png)

### Taskbar:
#### Pined
![taskbar_1](https://user-images.githubusercontent.com/11741404/56379680-9167ab80-6210-11e9-9175-fcce0dcac17c.png)

#### Pined and one unread message
![taskbar_3](https://user-images.githubusercontent.com/11741404/56379682-92004200-6210-11e9-81db-f958926b83fd.png)
#### Opened and has focus
![taskbar_2](https://user-images.githubusercontent.com/11741404/56379681-92004200-6210-11e9-9ed1-8418b7bbcc5e.png)

### Tile:
#### Medium and red accent color
![tile](https://user-images.githubusercontent.com/11741404/56379685-93ca0580-6210-11e9-91ae-49a61480e68c.png)


**Like always:** Let me know if you have any suggestions how I can make the new logo even better.

**Comment by Echolon** [comment]
Buddy, that looks so good, users might think XMPP is a Mircosoft thing ;)

Only point: May remove the tiny ticks in the small logo, so it is a simpler logo. However, not important!

Maybe also place a single "U" like the PowerPoint thing looks like.

Nice!

**Comment by COM8** [comment]
Thanks!
Remove triangles for the small icon: Yes that's a great idea.
"U": I was experimenting with that but it always looked like a German U-Bahn sign.
Here is an early prototype with it:
<img src="https://user-images.githubusercontent.com/11741404/56413345-800db600-6287-11e9-8b23-34614c08c6cc.jpeg" width="400">

For reference a German U-Bahm sign:
<img src="https://cdn.muenchen-p.de/.imaging/stk/responsive/image300/dms/aktuell-2016/mde/verkehr/verkehr-schild-ubahn/document/verkehr-schild-ubahn.jpg" width="400">

Source: [München.de](https://cdn.muenchen-p.de/.imaging/stk/responsive/image300/dms/aktuell-2016/mde/verkehr/verkehr-schild-ubahn/document/verkehr-schild-ubahn.jpg)

**Comment by Echolon** [comment]
Hi,

I personally wouldnt have related this to the Ubahn, as there probably also 'UWPX' is shown. What you could do instead is using an 'X' instead of 'U'
maybe call the app 'uwpX'   :)

**Comment by COM8** [comment]
I'm not really a fan of the X and/or changing the name capitalization. Sorry :D

Will have to play around with it a bit more.
Let's see if I find a font that does not immediately remember me on U-Bahn signs. 😁

**Comment by Supded** [comment]
Now embedded emoji did not match with system ones.

**Comment by Supded** [comment]
System revolver is water pistol in app. I think, it's better to use system emoji, if someone needs new emoji on old system - he can install them by guide from xda-developers.
https://files.catbox.moe/rca11v.png

**Comment by Supded** [comment]
System revolver is water pistol in app. I think, it's better to use system emoji, if someone needs new emoji on old system - he can install them by guide from xda-developers.
![Screenshot]
(https://files.catbox.moe/rca11v.png)

**Comment by Supded** [comment]
System revolver is water pistol in app. I think, it's better to use system emoji, if someone needs new emoji on old system - he can install them by guide from xda-developers.
![Screenshot](https://files.catbox.moe/rca11v.png)

**Comment by COM8** [comment]
I personally prefer to have the same Emoji on my phone that I have on my PC.
If you'd like to use all the latest Emoji, you can enable the UWPX "Emoji picker" via "Settings"->"Chat"->"Enable Emoji button".
Well in theory I could make this an option which is on by default, if there are more people that would like to see an option for that.

**Comment by Supded** [comment]
https://forum.xda-developers.com/windows-10-mobile/app-dhtemojiupdate-emojies-phone-t3855561

**Comment by COM8** [comment]
Well I don't think this will be a good way for all users.
* I personally wouldn't sideload an app that is not open source - who knows what is packaged with it
* Normal users that just wan't to use the app would never take the path to install an additional app where you would have to enable sideloading and the connect via the debug web page to your phone.

I also hate it, that they replaced the original revolver icon and it would be no problem to replace it back with the old one but then we get into license violation territory.

So: if there are multiple people that would like to see an option I will add one.

**Comment by evaryont** [comment]
2 things that annoy me with the latest version I've downloaded from the Microsoft Store on my Win10 desktop (v0.20.0.0):

* The font size of the text seems larger than the conversation body size. This may be a result of my 4k screen and Windows' scaling
* I can't use Enter to send a message, or one of the expected alternatives of Shift+Enter or Ctrl+Enter. I had to click on the send icon with my mouse. That's annoying on the desktop.

**Comment by COM8** [comment]
@evaryont Which fonts do you mean?
![2019-10-09 (2)](https://user-images.githubusercontent.com/11741404/66457431-b2e37a80-ea70-11e9-96dd-6a22a9f54193.png)

Did you enable "Enter to send" in the chat settings? For PCs it's disabled by default.

**Comment by evaryont** [comment]
The font size of the input box is larger than the message's size:

![image](https://user-images.githubusercontent.com/14547/66497980-d9270b80-eaac-11e9-9fda-a19198370e9a.png)

> Did you enable "Enter to send" in the chat settings? For PCs it's disabled by default.

Ah, apparently I didn't look at all of the settings. My bad!

**Comment by COM8** [comment]
@evaryont I've created a new issue (#73) for it.
I will have a look at it.
Thanks for reporting!

**Comment by COM8** [comment]
@evaryont Fixed it.
Should be included in this month's release.

**Comment by Echolon** [comment]
rel. [UI] Add chat screen: Inconsistent sizing of windows and overlapping #77
